apiVersion: v1
kind: Pod
metadata: # metadata include stuff that can indentify the pod like name and label
  name: hello-pod # any name u like
  labels:
    app: web #anylabel u want
    zone: prod
    version: v1
spec:
  containers:
    - name: node-container #anyname u want
      image: sithukyaw666/node-app:latest #docker image from image registry
      ports:
        - containerPort: 3000 #exposed port from docker image
