apiVersion: v1
kind: Service
metadata:
  name: svc-lb
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
    - port: 8080 # service endpoint port
      targetPort: 3000 #container port
  selector:
    app: web # must match developent label
